definitions:
  auth.LoginBody:
    properties:
      code:
        type: string
    type: object
  auth.TokenResponse:
    properties:
      token:
        type: string
    type: object
  collections.Collection:
    properties:
      created_at:
        example: "2025-01-01T12:00:00Z"
        type: string
      description:
        example: Описание коллекции
        type: string
      id:
        example: 1
        type: integer
      image_id:
        example: "12345"
        type: string
      title:
        example: Кольца
        type: string
    type: object
  internal_controller_banner.Banner:
    properties:
      collection_id:
        type: integer
      id:
        type: integer
      image_id:
        type: string
      mobile_image_id:
        type: string
    type: object
  items.Item:
    properties:
      collection_id:
        example: 1
        type: integer
      created_at:
        example: "2025-01-01T12:00:00Z"
        type: string
      description:
        example: Описание украшения
        type: string
      id:
        example: 1
        type: integer
      image_id:
        example: "67890"
        type: string
      title:
        example: Кольцо
        type: string
    type: object
  res.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  res.MessageResponse:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
  description: Описание API для сервиса Milutin Jewelry
  title: Milutin Jewelry API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Нужен код с почты админа, отправляет jwt токен
      parameters:
      - description: Данные для входа
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/auth.LoginBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.TokenResponse'
        "400":
          description: Неверный запрос
          schema:
            $ref: '#/definitions/res.ErrorResponse'
        "403":
          description: Неверный код
          schema:
            $ref: '#/definitions/res.ErrorResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/res.ErrorResponse'
      summary: Вход
      tags:
      - auth
  /auth/send-code:
    post:
      consumes:
      - application/json
      description: Отправляет код на почту админа
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/res.MessageResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/res.ErrorResponse'
      summary: Отправка кода
      tags:
      - auth
  /banners/all:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: Список всех баннеров
          schema:
            items:
              $ref: '#/definitions/internal_controller_banner.Banner'
            type: array
        "500":
          description: Ошибка сервера
          schema:
            $ref: '#/definitions/res.ErrorResponse'
      summary: Получение всех баннеров
      tags:
      - banners
  /banners/create:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: ID коллекции
        in: formData
        name: collection_id
        type: string
      - description: Изображение
        in: formData
        name: image
        required: true
        type: file
      - description: Изображение для мобильных устройств
        in: formData
        name: mobile_image
        required: true
        type: file
      produces:
      - application/json
      responses:
        "201":
          description: Баннер создан
          schema:
            $ref: '#/definitions/internal_controller_banner.Banner'
        "400":
          description: Неверный формат данных
          schema:
            $ref: '#/definitions/res.ErrorResponse'
        "401":
          description: Нет доступа
          schema:
            $ref: '#/definitions/res.ErrorResponse'
        "404":
          description: Коллекция не найдена
          schema:
            $ref: '#/definitions/res.ErrorResponse'
        "500":
          description: Ошибка сервера
          schema:
            $ref: '#/definitions/res.ErrorResponse'
      summary: Создание баннера
      tags:
      - banners
  /banners/delete/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: ID баннера
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Баннер успешно удален
          schema:
            $ref: '#/definitions/internal_controller_banner.Banner'
        "400":
          description: Неверный формат данных
          schema:
            $ref: '#/definitions/res.ErrorResponse'
        "401":
          description: Нет доступа
          schema:
            $ref: '#/definitions/res.ErrorResponse'
        "404":
          description: Баннер не найден
          schema:
            $ref: '#/definitions/res.ErrorResponse'
        "500":
          description: Ошибка сервера
          schema:
            $ref: '#/definitions/res.ErrorResponse'
      summary: Удаление баннера
      tags:
      - banners
  /collections/{id}:
    get:
      consumes:
      - application/json
      description: Получение данных одной коллекции по её ID
      parameters:
      - description: ID коллекции
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Данные коллекции
          schema:
            $ref: '#/definitions/collections.Collection'
        "400":
          description: Неверный формат данных
          schema:
            $ref: '#/definitions/res.ErrorResponse'
        "404":
          description: Коллекция не найдена
          schema:
            $ref: '#/definitions/res.ErrorResponse'
        "500":
          description: Ошибка сервера
          schema:
            $ref: '#/definitions/res.ErrorResponse'
      summary: Получение одной коллекции
      tags:
      - collections
  /collections/all:
    get:
      consumes:
      - application/json
      description: Получение списка всех коллекций
      produces:
      - application/json
      responses:
        "200":
          description: Список всех коллекций
          schema:
            items:
              $ref: '#/definitions/collections.Collection'
            type: array
        "500":
          description: Ошибка сервера
          schema:
            $ref: '#/definitions/res.ErrorResponse'
      summary: Получение всех коллекций
      tags:
      - collections
  /collections/create:
    post:
      consumes:
      - multipart/form-data
      description: Создание новой коллекции
      parameters:
      - description: Название коллекции
        in: formData
        name: title
        required: true
        type: string
      - description: Описание коллекции
        in: formData
        name: description
        type: string
      - description: Изображение коллекции
        in: formData
        name: image
        required: true
        type: file
      produces:
      - application/json
      responses:
        "201":
          description: Коллекция успешно создана
          schema:
            $ref: '#/definitions/collections.Collection'
        "400":
          description: Неверный формат данных
          schema:
            $ref: '#/definitions/res.ErrorResponse'
        "401":
          description: Нет доступа
          schema:
            $ref: '#/definitions/res.ErrorResponse'
        "500":
          description: Ошибка сервера
          schema:
            $ref: '#/definitions/res.ErrorResponse'
      summary: Создание коллекции
      tags:
      - collections
  /collections/delete/{id}:
    delete:
      consumes:
      - application/json
      description: Удаление существующей коллекции
      parameters:
      - description: ID коллекции
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Коллекция успешно удалена
          schema:
            $ref: '#/definitions/collections.Collection'
        "400":
          description: Неверный формат данных
          schema:
            $ref: '#/definitions/res.ErrorResponse'
        "401":
          description: Нет доступа
          schema:
            $ref: '#/definitions/res.ErrorResponse'
        "404":
          description: Коллекция не найдена
          schema:
            $ref: '#/definitions/res.ErrorResponse'
        "500":
          description: Ошибка сервера
          schema:
            $ref: '#/definitions/res.ErrorResponse'
      summary: Удаление коллекции
      tags:
      - collections
  /collections/update/{id}:
    put:
      consumes:
      - multipart/form-data
      description: Обновление данных существующей коллекции
      parameters:
      - description: ID коллекции
        in: path
        name: id
        required: true
        type: integer
      - description: Новое название коллекции
        in: formData
        name: title
        type: string
      - description: Новое описание коллекции
        in: formData
        name: description
        type: string
      - description: Новое изображение коллекции
        in: formData
        name: image
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: Коллекция успешно обновлена
          schema:
            $ref: '#/definitions/collections.Collection'
        "400":
          description: Неверный формат данных
          schema:
            $ref: '#/definitions/res.ErrorResponse'
        "401":
          description: Нет доступа
          schema:
            $ref: '#/definitions/res.ErrorResponse'
        "404":
          description: Коллекция не найдена
          schema:
            $ref: '#/definitions/res.ErrorResponse'
        "500":
          description: Ошибка сервера
          schema:
            $ref: '#/definitions/res.ErrorResponse'
      summary: Обновление коллекции
      tags:
      - collections
  /items/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: ID украшения
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/items.Item'
        "400":
          description: Invalid request parameters
          schema:
            $ref: '#/definitions/res.ErrorResponse'
        "404":
          description: Украшние не найдено
          schema:
            $ref: '#/definitions/res.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/res.ErrorResponse'
      summary: Получение украшения по ID
      tags:
      - items
  /items/collection/{id}:
    get:
      consumes:
      - application/json
      description: Получение украшений по ID коллекции, сортировка по дате создания
      parameters:
      - description: ID коллекции
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/items.Item'
            type: array
        "400":
          description: Invalid request parameters
          schema:
            $ref: '#/definitions/res.ErrorResponse'
        "404":
          description: Коллекция не найдена
          schema:
            $ref: '#/definitions/res.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/res.ErrorResponse'
      summary: Получение украшений по ID коллекции
      tags:
      - items
  /items/create:
    post:
      consumes:
      - multipart/form-data
      description: Создание украшения в коллекции
      parameters:
      - description: ID коллекции
        in: formData
        name: collection_id
        required: true
        type: integer
      - description: Название
        in: formData
        name: title
        type: string
      - description: Описание
        in: formData
        name: description
        type: string
      - description: Изображение
        in: formData
        name: image
        required: true
        type: file
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/items.Item'
        "400":
          description: Неверный формат данных
          schema:
            $ref: '#/definitions/res.ErrorResponse'
        "401":
          description: Нет доступа
          schema:
            $ref: '#/definitions/res.ErrorResponse'
        "404":
          description: Коллекции не существует
          schema:
            $ref: '#/definitions/res.ErrorResponse'
        "500":
          description: Ошибка сервера
          schema:
            $ref: '#/definitions/res.ErrorResponse'
      summary: Создание украшения
      tags:
      - items
  /items/delete/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: ID украшения
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Item successfully deleted
          schema:
            $ref: '#/definitions/items.Item'
        "400":
          description: Invalid request parameters
          schema:
            $ref: '#/definitions/res.ErrorResponse'
        "401":
          description: Нет доступа
          schema:
            $ref: '#/definitions/res.ErrorResponse'
        "404":
          description: Item not found
          schema:
            $ref: '#/definitions/res.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/res.ErrorResponse'
      summary: Удаление украшения
      tags:
      - items
  /items/update/{id}:
    put:
      consumes:
      - multipart/form-data
      parameters:
      - description: ID украшения
        in: path
        name: id
        required: true
        type: integer
      - description: Новое название
        in: formData
        name: title
        type: string
      - description: Новое описание
        in: formData
        name: description
        type: string
      - description: Новое изображение
        in: formData
        name: image
        type: file
      produces:
      - application/json
      responses:
        "201":
          description: Item successfully updated
          schema:
            $ref: '#/definitions/items.Item'
        "400":
          description: Invalid form data
          schema:
            $ref: '#/definitions/res.ErrorResponse'
        "401":
          description: Нет доступа
          schema:
            $ref: '#/definitions/res.ErrorResponse'
        "404":
          description: Item not found
          schema:
            $ref: '#/definitions/res.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/res.ErrorResponse'
      summary: Обновление украшения
      tags:
      - items
swagger: "2.0"
