version: '3.8'
name: 'milutin-jewellery'

services:
  proxy:
    image: grekas/jewellery-proxy
    container_name: proxy
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'

  migrate:
    image: grekas/jewellery-migrate
    container_name: migrate
    command: ['-path', '/migrations', '-database', '${POSTGRES_URL}', 'up']
    env_file:
      - .env
    depends_on:
      - db

  web:
    image: grekas/jewellery-web
    container_name: web
    restart: unless-stopped
    ports:
      - '3000:3000'
    env_file:
      - .env

  admin:
    image: grekas/jewellery-admin
    container_name: admin
    restart: unless-stopped
    ports:
      - '4000:4000'
    env_file:
      - .env

  api:
    image: grekas/jewellery-api
    container_name: api
    restart: unless-stopped
    ports:
      - '8080:8080'
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:alpine
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - '6379:6379'

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@admin.com'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
    depends_on:
      - db

volumes:
  pgdata:
