services:
  migrate:
    image: grekas/jewellery-migrate
    container_name: migrate
    command: ['-path', '/migrations', '-database', '${POSTGRES_URL}', 'up']
    environment:
      - POSTGRES_URL=${POSTGRES_URL}
    depends_on:
      - db

  web:
    image: grekas/jewellery-web
    container_name: web
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - API_URL=${API_URL}

  admin:
    image: grekas/jewellery-admin
    container_name: admin
    restart: unless-stopped
    ports:
      - 4000:4000
    environment:
      - API_URL=${API_URL}
      - JWT_SECRET=${JWT_SECRET}

  api:
    image: grekas/jewellery-api
    container_name: api
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - PORT=${API_PORT}
      - POSTGRES_URL=${POSTGRES_URL}
      - REDIS_URL=${REDIS_URL}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASS=${MAIL_PASS}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - OBJECT_STORAGE_ACCESS=${OBJECT_STORAGE_ACCESS}
      - OBJECT_STORAGE_SECRET=${OBJECT_STORAGE_SECRET}
      - OBJECT_STORAGE_ENDPOINT=${OBJECT_STORAGE_ENDPOINT}
      - OBJECT_STORAGE_BUCKET=${OBJECT_STORAGE_BUCKET}
      - OBJECT_STORAGE_REGION=${OBJECT_STORAGE_REGION}
      - JWT_TTL=${JWT_TTL}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - db
      - redis

  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_REGION_NAME=${MINIO_REGION_NAME}
    command: server /data --console-address ":9001"

volumes:
  pgdata:
  minio_data:
